### ISSUE TITLE
Repeated notifications, wrong time

### ISSUE THREAD

**Issue by Kreuger** [Futsch1/medTimer#572]
**Describe the bug**
This morning I got a notifcation 45 mins early. After taking my meds on time and marking them as taken, I keep getting the notification to take them.

**To Reproduce**
N/A

**Expected behavior**
Notifications on time and stop after marking taken.

**Screenshots*
N/A

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy A54
 - Android version: 14
 - App: 1.16.8

**Additional context:**
Started after the update installed yesterday.

**Comment by Futsch1** [comment]
Are you sure you are using v1.16.8? Because this should actually have fixed said problem?

If yes, can you please share your reminder setup for me to have a look and investigate?

**Comment by Kreuger** [comment]
I cant attach files so Im linking my screenshots [here](https://u.pcloud.link/publink/show?code=XZktwQ5ZKO3wyium0RuXqGPVyaRprQjTePAV) and [here](https://u.pcloud.link/publink/show?code=XZ5twQ5Zkgqj2nEDYDHwAu8O5M1sK77dMSDV) .

**Comment by Futsch1** [comment]
Thanks for the upload.

These screenshots show that each reminder has a different dose (8 mg, 10 mg and 40 mg). So this is obviously not the issue that was fixed with v1.16.8, which would have flooded you with reminders.

However, I would like to understand: You got three reminders, what type of reminders are these? Interval or time based reminders? What are the settings for them?

**Comment by Kreuger** [comment]
They 3 different meds and all reminders are for 5:30am, except on the weekend where it is delayed until 7am. There are no other settings that I am aware of.

**Comment by Futsch1** [comment]
I have a suspicion: Is it possible that the reminders were raised on the old version of the app and shown again after the update was installed? Because the app has a functionality that restores reminders after an update. This is hard to test to be honest and might contain a bug.

Or has it appeared again since then?

**Comment by Kreuger** [comment]
No its definitely still happening. The only way to stop it is if I leave the notifications. Im going to uninstall the app and start fresh.

**Comment by Kreuger** [comment]
Deleting the app and starting fresh has fixed it. So maybe it was something in my database that messed things up? Anyway Im closing this.

**Comment by Futsch1** [comment]
I can reproduce it now with another data set. I will reopen this to track the fix and get to the bottom of it.

**Comment by Kreuger** [comment]
Well done!
